CREATE TABLE schedule (
     CODE         UUID NOT NULL,
     TITLE        VARCHAR(255) NOT NULL,
     DESCRIPTION  TEXT,
     DAT_CREATION TIMESTAMP NOT NULL,
     DAT_UPDATE   TIMESTAMP NOT NULL,
     EXPIRATION   TIMESTAMP,
     PRIMARY KEY (CODE)
);