CREATE TABLE vote (
     CODE             UUID NOT NULL,
     OPTION           VARCHAR(3) NOT NULL,
     DAT_CREATION     TIMESTAMP NOT NULL,
     CODE_SCHEDULE    UUID NOT NULL,
     PRIMARY KEY (CODE),
     FOREIGN KEY (CODE_SCHEDULE) REFERENCES schedule(CODE)
);