version: '3'
services:
  local-postgres:
    image: postgres
    container_name: postgres
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: sicred
      POSTGRES_USER: sicred
      POSTGRES_PASSWORD: sicred
    volumes:
      - ~/data:/var/lib/postgresql/data
    networks:
      - postgres-network
  local-pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "gleidson.ferreirasantos@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "sicred"
    ports:
      - "16543:80"
    depends_on:
      - local-postgres
    networks:
      - postgres-network
  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - "/home/$USER/workspace/"
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

networks:
  postgres-network:
    driver: bridge