version: '3'
services:
  local-postgres:
    image: postgres
    container_name: postgres
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: sicred
      POSTGRES_USER: sicred
      POSTGRES_PASSWORD: sicred
    volumes:
      - ~/data:/var/lib/postgresql/data
    networks:
      - postgres-network
  local-pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "gleidson.ferreirasantos@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "sicred"
    ports:
      - "16543:80"
    depends_on:
      - local-postgres
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge