spring:
  rabbitmq:
    host: localhost
    port: 5672
    password: rabbitmq
    username: rabbitmq
  application:
    name: sicred-api
  datasource:
    driver-class-name: org.postgresql.Driver
    username: sicred
    password: sicred
    url: jdbc:postgresql://localhost:15432/sicred
    platform: postgres
  flyway:
    enabled: false
  #    baseline-on-migrate: true
#    enabled: true
#    locations: classpath:db/migration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    openInView: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false