
spring:
  rabbitmq:
    host: localhost
    port: 5672
    password: rabbitmq
    username: rabbitmq
  application:
    name: sicred-api
  datasource:
    driver-class-name: org.postgresql.Driver
    username: sicred
    password: sicred
    url: jdbc:postgresql://localhost:15432/sicred
    platform: postgres
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    openInView: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

feign:
  client:
    devhub:
      cpf:
        uri: https://ws.hubdodesenvolvedor.com.br/v2/cpf/?token=93561250HZYxvoczWF168922000
    config:
      default:
        connectTimeout: 15000
        readTimeout: 15000
        loggerLevel: basic
  hystrix:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE