spring:
  application:
    name: sicred-api
  datasource:
    driver-class-name: org.postgresql.Driver
    username: sicred
    password: sicred
    url: jdbc:postgresql://localhost:5432/sicred
    platform: postgres
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
    openInView: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false