spring:
    kafka:
      consumer:
          bootstrap-servers: localhost:9092
          group-id: sicred-messaging
          auto-offset-reset: earliest
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      producer:
          bootstrap-servers: localhost:9092
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.apache.kafka.common.serialization.StringSerializer
    rabbitmq:
        host: localhost
        port: 5672
        password: rabbitmq
        username: rabbitmq
    application:
        name: sicred-api
    datasource:
        driver-class-name: org.postgresql.Driver
        username: sicred
        password: sicred
        url: jdbc:postgresql://localhost:15432/sicred
        platform: postgres
    flyway:
        baseline-on-migrate: true
        enabled: true
        locations: classpath:db/migration
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        generate-ddl: false
        hibernate:
            ddl-auto: none
        show-sql: true
        openInView: false
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false